### ISSUE TITLE
recordId "pop-under" not working...

### ISSUE THREAD

**Issue by savage25** [douglascayers/sfdx-record-create-url-component#1]
I just implemented this, thank you so much!
I believe there may be an issue though: When I opening the link into a new window (using target="_blank") and send "recordId", I see the "new record" popup come up briefly, but then it closes as the underlying record loads.  If I do not use recordId parameter (so that the background stays blank), it works.  It also works if I do not open into a new window (no "target" on the href)

**Comment by douglascayers** [comment]
Thanks @savage25. In testing tonight, I've noticed that the component needs to give the page a little more time for the background to load the record before trying to show the "create record" action. If the navigation is slow, then it happens **after** the "create record" modal is shown and thus the modal is closed prematurely. This is all a hack, but to add to the hackiness, I think I'll just add a timeout of ~1 second and hope for the best.
