### ISSUE TITLE
Blank fieldName Parameters cause failure

### ISSUE THREAD

**Issue by savage25** [douglascayers/sfdx-record-create-url-component#2]
If you pass a fieldName parameter with no value for a lookup field (like AccountId), the new record popup will fail.

I fixed by adding check for value to line 72 of the Helper
if ( fieldDescribeMap.hasOwnProperty( fieldName ) && fieldDescribeMap[fieldName].createable **&& pageRef.state[fieldName]** ) {

**Comment by douglascayers** [comment]
Thanks @savage25
